### ISSUE TITLE
Barrier is Starting

### ISSUE THREAD

**Issue by MatthewLomando** [ARM-software/speculation-barrier#4]
I am having a problem when I try to host the barrier server on my windows device. When I try to connect to it on my Linux device it gets stuck on the message that barrier is starting. If I host the server on linux it works fine. But it dose not work when I try to host the server on windows. BTW your software is great and It is also a life saver.

**Comment by jgreenhalgh-arm** [comment]
Thanks for your report, I think you may have the wrong project! This project provides C header wrappers of the `__builtin_load_no_speculate` builtin functions - as such there is no server to start.
